//------------------------------------------------------------------------------
// <auto-generated>
//     ??ì½”ë“œ???œí”Œë¦¿ì—???ì„±?˜ì—ˆ?µë‹ˆ??
//
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©??‘ìš© ?„ë¡œê·¸ë¨?ì„œ ?ˆê¸°ì¹??Šì? ?™ì‘??ë°œìƒ?????ˆìŠµ?ˆë‹¤.
//     ???Œì¼???˜ë™?¼ë¡œ ë³€ê²½í•˜ë©?ì½”ë“œê°€ ?¤ì‹œ ?ì„±????ë³€ê²??´ìš©????–´?ë‹ˆ??
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockCalc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public System.DateTime Date { get; set; }
        public string StockId { get; set; }
        public double Close { get; set; }
        public Nullable<double> PER { get; set; }
        public double StockHolding { get; set; }
        public double MarketCap { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
