//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockCalc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int StrategyId { get; set; }
        public string StockId { get; set; }
        public System.DateTime BuyDate { get; set; }
        public double BuyPrice { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public double TradeER { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Strategy Strategy { get; set; }
    }
}
